### ISSUE TITLE
Creating a PDF of completly finalised VTU lab materials

### ISSUE THREAD

**Issue by AbhiiGatty** [so-sc/VTU-Lab-Material#12]

**Comment by haxzie** [comment]
Hey @Hitoshirenu , Do you think creating a PDF kills the purpose of having a repository with all the files? I think we can pass on creating the PDF of programs anymore. To bring about the change, we need to drop the old practices. :smile:

**Comment by haxzie** [comment]
@rumaan Whattya think about this?

**Comment by rumaan** [comment]
oops i am seeing this now
