### ISSUE TITLE
program is missing.

### ISSUE THREAD

**Issue by swaaz** [so-sc/VTU-Lab-Material#27]
There are no programs in the files mentioned below
- VTU-Lab-Material/sem-1-2/18CPL17-27_COMPUTER_PROGRAMMING_LABORATORY/Program-02/program-01.c
- VTU-Lab-Material/sem-1-2/18CPL17-27_COMPUTER_PROGRAMMING_LABORATORY/Program-02/program-02.c
- VTU-Lab-Material/sem-1-2/18CPL17-27_COMPUTER_PROGRAMMING_LABORATORY/Program-02/program-03.c
- VTU-Lab-Material/sem-1-2/18CPL17-27_COMPUTER_PROGRAMMING_LABORATORY/Program-02/program-04.c

**Comment by suhanacharya** [comment]
The problem is, program-03.c and program-04.c have the same **description**. There isn't really 15 programs for Sem 1. :smile: 
Although program-04.c already exists.

**Comment by rumaan** [comment]
@suhanacharya  #30
