### ISSUE TITLE
Program complexities and intensions

### ISSUE THREAD

**Issue by Hitoshirenu** [so-sc/VTU-Lab-Material#5]
The programs as in 15CSL77 are far too complex as people won't need material that's really easy to remember and digest like little chunks. Just the first program required them to remember three files where people don't really know the difference between JS and PHP two days prior to external. So lets keep it simple and not too fancy.
Keep in mind that it need to be developer standards just easy learning material. @haxzie Let's have a review before any merging code.

**Comment by haxzie** [comment]
Sure, I'll lock the merge access to only few people so they can review everything.

**Comment by Hitoshirenu** [comment]
:heart_eyes: Great!
