### ISSUE TITLE
Refactor Suggestion 😉

### ISSUE THREAD

**Issue by rumaan** [so-sc/VTU-Lab-Material#8]
How about having the programs (directory structure) sectioned as:

<pre>
-> SEM-01
    -> PCD LAB
    -> SOME NEW LAB
-> SEM-02
...
</pre>

because in some semesters based on the `Branch` they might have different labs. (ex: IS 6th sem didn't have CG)

----
Or having different `git branches` for different `branches (engineering)` 🤡 since the repo is named <b>VTU-Lab-Material</b>.😃

**Comment by rumaan** [comment]
is this repo specific to just Lab Programs (I mean any PDF's, reference links added too?) of CS/IS @Hitoshirenu

**Comment by Hitoshirenu** [comment]
> How about having the programs (directory structure) sectioned as:
> 
> -> SEM-01
>     -> PCD LAB
>     -> SOME NEW LAB
> -> SEM-02
> ...
> 
> because in some semesters based on the `Branch` they might have different labs. (ex: IS 6th sem didn't have CG)
> 
> Or having different `git branches` for different `branches (engineering)` clown_face since the repo is named VTU-Lab-Material.smiley

@rumaan 
Isn't the current file hierarchy already satisfying the doubt? 
What the current implemented structure looks like 
```sh
├── LICENSE
├── readme.md
├── sem-1-2
│   └── readme.md
.
.
.
├── sem-5
│   ├── computer_science
│   ├── electronics_and_communication
│   ├── information_science
│   └── readme.md
├── sem-6
│   ├── computer_science
│   ├── electronics_and_communication
│   ├── information_science
│   └── readme.md
├── sem-7
│   ├── computer_science
│   │   ├── 15CSL76_MACHINE_LEARNING_LABORATORY
│   │   │   ├── 01. Find-S Algorithm.ipynb
│   │   │   ├── 01. Find-S Algorithm.py
│   │   │   ├── 02. Candidate Elimination.ipynb
.
.
.
.
```
I took into account what you said before creating this repo and finalized this file structure after trying a few different hierarchies. This is we have according to **Department** as well as **Semester**. I hope that clears any doubts. 
Cheers! :beer:

**Comment by Hitoshirenu** [comment]
> is this repo specific to just Lab Programs (I mean any PDF's, reference links added too?) of CS/IS @Hitoshirenu

@rumaan 
Yes, i plan to make some pdfs of the final content that fills the repo but before which i'll have a word with one of the lab lecturer in charge.
Plans also include a set of possible VIVA questions too in the repo which would make this more favorable to others.

**Comment by rumaan** [comment]
If that's how it is already then it's cool! 
I got a little confused since some of the folders have a lab program regardless of what lab and branch they are from.:smile:

**Comment by Hitoshirenu** [comment]
> If that's how it is already then it's cool!
> I got a little confused since some of the folders have a lab program regardless of what lab and branch they are from.smile

@rumaan 
Can you specify which ones? i'll change the main README to be a bit more clear too!

**Comment by rumaan** [comment]
Sem 1-4 aren't structured properly I guess.:smile:

**Comment by rumaan** [comment]
#10 👍

**Comment by Hitoshirenu** [comment]
@rumaan 
#9
